In [1]:
import numpy as np

In [11]:
a = np.array([0, 1, 2, 3, 4, 5])
print(a)
print(np.shape(a))

[0 1 2 3 4 5]
(6,)


In [12]:
b = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
print(b)
print(np.shape(b))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(3, 3)


In [13]:
c = np.array([[[0, 1, 2], [3, 4, 5]], [[5, 4, 3], [2, 1, 0]]])
print(c)
print(np.shape(c))

[[[0 1 2]
  [3 4 5]]

 [[5 4 3]
  [2 1 0]]]
(2, 2, 3)


In [10]:
d = np.zeros(8)
print(d)

e = np.ones(8)
print(e)

f = np.arange(8)
print(f)

[0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1.]
[0 1 2 3 4 5 6 7]


In [14]:
a = np.array([[0, 1, 2], [3, 4, 5]])

print(a)
print()
print(a + 3)
print()
print(a * 3)

[[0 1 2]
 [3 4 5]]

[[3 4 5]
 [6 7 8]]

[[ 0  3  6]
 [ 9 12 15]]


In [15]:
b = np.array([[0, 1, 2], [3, 4, 5]])
c = np.array([[2, 0, 1], [5, 3, 4]])

print(b)
print()
print(c)
print()
print(b + c)
print()
print(b * c)


[[0 1 2]
 [3 4 5]]

[[2 0 1]
 [5 3 4]]

[[2 1 3]
 [8 7 9]]

[[ 0  0  2]
 [15 12 20]]


In [16]:
a = np.array([1, 2, 3, 4, 5])
print(a[3])

a[2] = 9
print(a)

4
[1 2 9 4 5]


In [18]:
b = np.array([[0, 1, 2], [3, 4, 5]])
print(b[1, 2])

b[1,2] = 9
print(b)

5
[[0 1 2]
 [3 4 9]]


In [21]:
c = np.array([[0, 1, 2], [3, 4, 5]])
print(c[1, :])

print()

c[:, 1] = np.array([6, 7])
print(c)


[3 4 5]

[[0 6 2]
 [3 7 5]]


In [22]:
def my_func(x):
    y = x * 2 + 1
    return y

a = np.array([[0, 1, 2], [3, 4, 5]])
b = my_func(a)

print(b)

[[ 1  3  5]
 [ 7  9 11]]


In [24]:
a = np.array([[0, 1, 2], [3, 4, 5]])

print("合計:", np.sum(a))
print("平均:", np.average(a))
print("最大値:", np.max(a))
print("最小値:", np.min(a))

合計: 15
平均: 2.5
最大値: 5
最小値: 0


In [25]:
a = np.array([[0, 1, 2], [3, 4, 5]])
b = np.array([[5, 4, 3], [2, 1, 0]])

print(a + b)
print(a - b)
print(a * b)

[[5 5 5]
 [5 5 5]]
[[-5 -3 -1]
 [ 1  3  5]]
[[0 4 6]
 [6 4 0]]
